### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by m4cgregor** [AgusRambal/Tarea1#1]
Faltó poner el archivo .gitignore en la carpeta raiz. 

Por eso su subieron las carpetas "Libraries", que no tendrían que estar...

**Comment by m4cgregor** [comment]
En realidad, el problema es que tiene  extensión ".txt"  la enxtensión, tiene que ser ".gitignore"

**Comment by AgusRambal** [comment]
Listo, ahora funciona!
